# Generated by Django 3.2 on 2023-04-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230419_1617'),
        ('reviews', '0002_initial'),
    ]

    operations = [
    ]
